---
title: "tidy"
author: "Jake Eisaguirre"
date: "3/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
```

# Swath
```{r}
swath <- read.csv(here("data", "swath.csv")) %>% 
  select(!c(survey_year, size, disease, notes, site_name_old)) %>% 
  unnest()

  
swath_wide <- swath %>% 
  pivot_wider(id_cols = c(campus, method, year, depth,
                          month, day, site, zone, transect, observer),
              names_from = classcode, values_from = count)


clean_swath <- swath_wide %>% 
  rowwise() %>% 
  mutate(MACPYRAD = sum(MACPYRAD),
         PATMIN = sum(PATMIN),
         HENLEV = sum(HENLEV),
         STRPURAD = sum(STRPURAD),
         MESFRAAD = sum(MESFRAAD),
         PISGIG = sum(PISGIG),
         DERIMB = sum(DERIMB),
         PISOCH = sum(PISOCH),
         HALRUF = sum(HALRUF),
         HALWAL = sum(HALWAL),
         HALKAM = sum(HALKAM),
         PISSPP = sum(PISSPP),
         PANINT = sum(PANINT)) %>% 
  unnest(c(11:184)) %>% 
  mutate_all(na_if, "")
  
is.na(clean_swath$observer)

for(i in 11:184){
  clean_swath[is.na(clean_swath[,i]), i] = 0
}


write.csv(clean_swath, here("data", "clean_swath.csv"))
```

# upc
```{r}

raw_upc <- read_csv(here("data", "upc.csv")) %>% 
  select(!c(survey_year, notes, site_name_old, pct_cov)) %>% 
  unnest()

upc_wide <- raw_upc %>% 
  pivot_wider(id_cols = c(campus, method, year, month, day, site, zone, transect),
                       names_from = classcode, values_from = count)

for(i in 9:95){
  upc_wide[is.na(upc_wide[,i]), i] = 0
}

write.csv(upc_wide, here("data", "clean_upc.csv"))

```

#fish
```{r}

raw_fish <- read_csv(here("data", "fish.csv")) %>% 
  select(!c(survey_year, notes, site_name_old, LOOKEDFOR))

upc_fsih <- raw_fish %>% 
  pivot_wider(id_cols = c(campus, method, year, month, day, site, zone, transect, pct_cov),
                       names_from = classcode, values_from = count)

```

